# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b92c6e007014e5cdbb9d0060a767afc2420fe1066ca7b0cb448ffcf3ae0d8c9d508b6298ed9609ea94bb69a66a9ff049efaa6930e59fbbd552979212129f0247

test:
  secret_key_base: b33026db6657be4857d5961bbb685fe51b97e4201ce32c1c874589dca52719713800a57fceebb9283a924a0bba71404e67f6e93d07f57ba14d5ab877a20c3e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
